name: Build and publish user guide documentation to GitHub Pages

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            HUGO_VERSION: 0.120.4
        steps:
            -   name: Install Hugo CLI
                run: |
                    wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
                    && sudo dpkg -i ${{ runner.temp }}/hugo.deb   

            -   name: Install Dart Sass
                run: sudo snap install dart-sass

            -   name: Setup node
                uses: actions/setup-node@v4
                with:
                    node-version: 18

            -   name: Install Docsy dependencies
                run: |
                    npm install postcss postcss-cli autoprefixer

            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    submodules: recursive
                    fetch-depth: 0

            -   name: Build with Hugo
                env:
                    # For maximum backward compatibility with Hugo modules
                    HUGO_ENVIRONMENT: production
                    HUGO_ENV: production
                run: hugo --gc --minify

            -   name: Deploy to GitHub Pages
                if: success()
                uses: crazy-max/ghaction-github-pages@v4
                with:
                    target_branch: gh-pages
                    build_dir: public
                    keep_history: true
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
